# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(310, 348)
        MainWindow.setMaximumSize(QtCore.QSize(400, 400))
        MainWindow.setSizeIncrement(QtCore.QSize(300, 500))
        MainWindow.setStyleSheet("*{\n"
"    background-color: rgb(0, 79, 116);\n"
"   border:none;\n"
"   background-color: transparent;\n"
"   background: transparent;\n"
"   padding: 0;\n"
"   margin:0;\n"
"   color:#fff;\n"
"}\n"
"#centralwidget, #mainBodyContent, #AccBtn{\n"
"background-color: #003f5c;\n"
"}\n"
"#leftPart{\n"
"background-color: #ffffff;\n"
"\n"
"}\n"
"\n"
"#pushButton{\n"
"background-color: #00557f;\n"
"color: #ffffff;\n"
"border-radius: 10px 10px 10px 10px;\n"
"padding: 3px 5px;\n"
"}\n"
"QLineEdit{\n"
"background-color: transparent;\n"
"color: #ffffff;\n"
"border-radius: 10px 10px 10px 10px;\n"
"border: 2px solid #00557f;\n"
"padding: 3px 5px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rightPart = QtWidgets.QWidget(parent=self.centralwidget)
        self.rightPart.setObjectName("rightPart")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.rightPart)
        self.lineEdit.setGeometry(QtCore.QRect(70, 160, 141, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.rightPart)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 210, 141, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.rightPart)
        self.pushButton.setGeometry(QtCore.QRect(80, 290, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=self.rightPart)
        self.label.setGeometry(QtCore.QRect(80, 20, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.rightPart)
        self.label_2.setGeometry(QtCore.QRect(80, 250, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.rightPart)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 30, 181, 161))
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/Copie de Sauatge (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.horizontalLayout.addWidget(self.rightPart)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Nom d\'utilisateur"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Mot de passe"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Application BG Blast"))
        self.label_2.setText(_translate("MainWindow", "Continuer autnat que visiteur?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
